# Generated by Django 3.0.5 on 2020-09-15 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200915_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_item',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount offer', max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='product_item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per item', max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
    ]
