# Generated by Django 3.0.5 on 2020-09-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200910_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_item_images',
            name='image',
            field=models.ImageField(default='default-product.jpg', upload_to='Uploads'),
        ),
    ]
