# Generated by Django 3.0.5 on 2020-09-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200916_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='razpayorder_id',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
