# Generated by Django 3.0.5 on 2020-09-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20200917_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='payondelivery',
            field=models.BooleanField(default=False),
        ),
    ]
