# Generated by Django 3.0.5 on 2020-09-17 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20200917_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='customer',
        ),
    ]
