# Generated by Django 3.0.5 on 2020-09-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_paymentdetail_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='status',
            field=models.CharField(default='Created', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='state',
            field=models.CharField(max_length=30),
        ),
    ]
