# Generated by Django 3.0.5 on 2020-09-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200917_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='razpayorder_id',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
